### ISSUE TITLE
Wix Native Navigation

### ISSUE THREAD

**Issue by odesey** [Agontuk/react-native-collapsible-toolbar#1]
Will this package work with [Wix react-native-navigation](https://github.com/wix/react-native-navigation) ?

Also can you include a more detailed example? Would be helpful for beginners like myself

Thanks.

**Comment by Agontuk** [comment]
yes it should work, I'm currently using it with RNN. I'm planning to add an example project as soon as possible.

**Comment by odesey** [comment]
Awesome, last question.

What am I returning from the    ` renderNavBar={this.renderNavBar}` function? `this.props.navigator.?`

Thanks.

**Comment by Agontuk** [comment]
You should return a navbar view like:
```js
renderNavBar = () => (
    <View>
        <BackButton />
        <Title />
    </View>
)
```

**Comment by odesey** [comment]
Thanks, I have it working now.

How can I adjust the height of the navBar when its collapsed? I am returning the following navBar but the height is too much and I cannot decrease it:

```javascript
  renderNavBar = () => (
    <View style={{ height: 10 }}>
      <Icon name="ios-arrow-back" size={36} color="#900" style={{ paddingVertical: 0, height: 10 }} />
    </View>
  );
```

**Comment by Agontuk** [comment]
nav bar height is fixed (56 for android, 44 for ios), you just have to render what you want inside of it. I'll try to push the example tonight.

**Comment by odesey** [comment]
Solved, removing `translucentStatusBar` removed the extra space. 

Thanks.
