### ISSUE TITLE
local imageSource

### ISSUE THREAD

**Issue by odesey** [Agontuk/react-native-collapsible-toolbar#5]
Is there anyway to use a local file ie `require("../../../app/images/my_image.png")` for the image source prop? I've tried the following:

`require("../../../app/images/my_image.png")`
`("../../../app/images/my_image.png")`
`"../../../app/images/my_image.png"`

None of those seem to work.

Thanks.

**Comment by Agontuk** [comment]
you can use the `renderToolBar` prop to render your local image like this -
```js
renderToolBar={() => <Image source={require('../img.jpg')} />}
```
