### ISSUE TITLE
 Curved shape at the bottom

### ISSUE THREAD

**Issue by AbhishekDS-Userfacet** [Agontuk/react-native-collapsible-toolbar#6]
How to achieve a curved shape at the bottom instead of rectangular (Design as shown in image)?

![circular toolbar](https://user-images.githubusercontent.com/37110839/40642018-544904a0-6339-11e8-92f0-0a5080d8a06f.png)

**Comment by Agontuk** [comment]
You can use `renderToolBar` prop to control what your image is gonna look like.
